### ISSUE TITLE
Cool just what I was looking for

### ISSUE THREAD

**Issue by sarsenal** [AccelerateNetworks/FreeSWITCH-push#1]
Where are you putting the script for Freeswitch to pick it up?

Does it work for Apple devices running zoiper?  You have it listed but I don't see where it does it.

Also, have you ported it: FCM?  Below is the info they had on their website. I am going to test and add to the interface of FusionPBX (Freeswitch).  I think this is important.  Saves our batteries!  Why more people are not trying to do this surprises me. I think only 3cx was the only I saw so far.

Great simple approach.  

Thanks again,
Jason

FCM is the new version of GCM under the Firebase brand. It inherits GCM’s core infrastructure, with new SDKs to make Cloud Messaging development easier.

Benefits of upgrading to FCM SDK include:

Simpler client development. You no longer have to write your own registration or subscription retry logic.
An out-of-the-box notification solution. You can use Firebase Notifications, a serverless notifications solution with a web console that lets anyone send notifications to target specific audiences based on Firebase Analytics insights.

**Comment by thefinn93** [comment]
>Where are you putting the script for Freeswitch to pick it up?

From the readme:
>I have two dialplan rules to make this work. First
>
>`set: sleeptime=${system push.py  push ${destination_number}@${domain_name}}`
>
>and second:
>
>`sleep: ${sleeptime}`


> Does it work for Apple devices running zoiper? You have it listed but I don't see where it does it.

Haven't tested it on iOS. I played with Zoiper's push stuff a bit and there is some preliminary code for it, but I don't remember if I ever got it working. Mostly been focusing on Linphone.


>Also, have you ported it: FCM?

I haven't looked at FCM, but Linphone uses GCM so I use GCM.


None of this code is terribly complicated, it should be pretty trivial to adapt it to whatever client software you use (as long as it supports push notifications of some kind). Please make a pull request if you add support for additional clients.

**Comment by sarsenal** [comment]
Finn,
I mean what path did you put the file in so picks it up from the correct
location?  Will it just pick it up as long as it is in the path of the
web user?  I was just about to load it and play with it.  Had to make
the change for the new code they don't give API access any long for the
old GCM system.  Just need to fire it up in a bit.'

Thanks,
Jason

**Comment by thefinn93** [comment]
Ah, I didn't actually put it in the path, i just provided the full path I believe. so really more like `${system /path/to/push.py ...}`

**Comment by thefinn93** [comment]
and please PR the changes for GCM back. That might explain why we've been having issues of late. I haven't looked at this in several months

**Comment by sarsenal** [comment]
Will do.

**Comment by danry25** [comment]
@sarsenal A rewrite of this has been completed on ommit b2c7bea2919902a5dfb127bef4c0ec498679ffd9 which adds Firebase Cloud Messaging support. We are also tuning [Linphone Android](https://github.com/AccelerateNetworks/linphone-android/issues?q=is%3Aopen+is%3Aissue) to enable it to work well with Freeswitch over suboptimal cellular data connections.
