### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by nconder** [AccelerateNetworks/FreeSWITCH-push#2]
Great solution. Does this also support Android Linphone and Zoiper? If so could you give an example of a pushkeys.conf or is it not needed?

**Comment by thefinn93** [comment]
It supports Android Linphone, if you build your own copy of Linphone. Format of `keys.conf` is like this:

```json
{
  "gcm": {
    "GCM ID": "GCM key"
  }
}
```

Where GCM ID and GCM key are the id and key from Google. You can provide as a list of them and it will pick the one that the client requested. This GCM ID then needs to be baked into the Linphone build. I forget exactly where, but it's in one of their global consts and shouldn't be too hard to find.


I forget if it works with Zoiper, maybe @danry25 knows? I forget if he has anyone using Zoiper with push.

**Comment by danry25** [comment]
Nope, never got push with Zoiper set up. Might look into it in the future, we have a few clients using it on iPhone for paging, it'd be nice if they could receive calls reliably.

**Comment by danry25** [comment]
@nconder Commit b2c7bea2919902a5dfb127bef4c0ec498679ffd9 adds Firebase Cloud Messaging support while removing the requirement of Python. We are also tuning [Linphone Android](https://github.com/AccelerateNetworks/linphone-android/issues?q=is%3Aopen+is%3Aissue) to enable it to work well with Freeswitch over suboptimal cellular data connections.
