### ISSUE TITLE
GCM deprecated as of 2019-04-11

### ISSUE THREAD

**Issue by schbrongx** [AccelerateNetworks/FreeSWITCH-push#3]
From https://developers.google.com/cloud-messaging/registration
As of April 10, 2018, Google has deprecated GCM. The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019. Migrate GCM apps to Firebase Cloud Messaging (FCM), which inherits the reliable and scalable GCM infrastructure, plus many new features. See the migration guide to learn more: https://developers.google.com/cloud-messaging/android/android-migrate-fcm

**Comment by danry25** [comment]
Ah, neat, most of our clients aren't using push message based registration for their mobile apps. Using apps that default to IPv6 does wonders for delivering inbound calls over mobile networks (most are IPv6 first, with legacy IPv4 provided inconsistently via CGNAT).

We used to use Linphone with this FreeSWITCH Push module in the past (just changing out the GCM keys in Linphone), but newer builds of Linphone v4.0.1 seem to be quite crash prone on modern Android (having tested the Play Store & F-Droid versions on various devices running Android 8.1 & Android 9).

If you want to fork and fix this, feel free! This could likely be adapted to work with Zoiper (who provides a central push gateway IIRC) or another VOIP app pretty easily.

**Comment by danry25** [comment]
Looks like this is a one line update to change the [url](https://github.com/AccelerateNetworks/FreeSWITCH-push/blob/master/push.py#L57) to https://fcm.googleapis.com/fcm/

**Comment by danry25** [comment]
@schbrongx Commit b2c7bea2919902a5dfb127bef4c0ec498679ffd9 fixes this issue adding Firebase Cloud Messaging support. We are also tuning [Linphone Android](https://github.com/AccelerateNetworks/linphone-android/issues?q=is%3Aopen+is%3Aissue) to enable it to work well with Freeswitch over suboptimal cellular data connections.
